### ISSUE TITLE
All requirements completed, but can't start the bot

### ISSUE THREAD

**Issue by Uselessclod** [mirage2032/Scrap.tf-RaffleBot#4]
hello, can you help me? i tried to start it and it sends this error. I installed selenium, bs4 and requests, started run.bat and this happened:

`Traceback (most recent call last):
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Couldn't find file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qwert\Downloads\Scrap.tf-RaffleBot-master\src\rafflebot.py", line 149, in <module>
    RaffleBot(path)
  File "C:\Users\qwert\Downloads\Scrap.tf-RaffleBot-master\src\rafflebot.py", line 23, in __init__
    self.generateCookie()  # if not ask user to login using selenium to generate one
  File "C:\Users\qwert\Downloads\Scrap.tf-RaffleBot-master\src\rafflebot.py", line 52, in generateCookie
    driver = webdriver.Chrome(webdriver_path, options=options)
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

i installed 32 bit for windows, but it says "Only local connections are allowed.", i started with it opened, and nothing happened, and i dont know how to add it in path as error says 
>'chromedriver.exe' executable needs to be in PATH.

tried to reinstall, but it doesn't work for me

**Comment by Uselessclod** [comment]
readme says: Chromium and it's Webdriver are downloaded automatically if not already present.
but its not downloading when i start program

**Comment by mirage2032** [comment]
Are you using python 3.8 or higher?
Are 'RUN.bat', 'chromiumdl.py' and 'rafflebot.py' the only files in the directory?
I suspect it might be a problem with the way i handle the PATH, I will do my best to replicate the problem and fix it.

**Comment by Uselessclod** [comment]
Yes, i am using python 3.9.4
you can see 2 other folders on screenshot
![img](https://user-images.githubusercontent.com/82600279/114902414-ff66fd80-9e3f-11eb-9237-02d27c460111.png)

**Comment by mirage2032** [comment]
try deleting the chromium and pycache and try again

**Comment by Uselessclod** [comment]
folder chromium is empty and pycache contains "chromiumdl.cpython-39.pyc"

**Comment by Uselessclod** [comment]
It started working after deleting these folders and reinstalling, thank you!

**Comment by mirage2032** [comment]
I believe that the first time you launched it somehow it crashed, and just created the 'Chromium' directory.
After that because the directory existed it tought it had Selenium even if it didn't.
Will update it to verify that Selenium is actually existing and in working order
